import { readFileSync } from "node:fs";
import path from "node:path";
import Image from "next/image";
import type { Metadata } from "next";
import { CtaButton } from "@/components/shared/cta-button";
import { SectionShell } from "@/components/shared/section-shell";

type ReportStatus = "pass" | "warn" | "fail";
type ScenarioStatus = "pass" | "warn" | "fail";
type ScenarioSeverity = "critical" | "warning";

type CheckResult = {
  name: string;
  status: "pass" | "fail";
  severity: ScenarioSeverity;
  expected?: string;
  actual?: string | number | boolean | null;
  message?: string;
};

type ScenarioResult = {
  scenario: {
    name: string;
    viewport: {
      width: number;
      height: number;
    };
    colorScheme: string;
    reducedMotion: string;
    contentVariant: string;
    deviceScaleFactor: number;
    assetMode?: string;
    severity: ScenarioSeverity;
  };
  status: ScenarioStatus;
  checks: CheckResult[];
  metrics: {
    cls?: number;
    ctaWidth?: number;
    ctaHeight?: number;
    scrollWidth?: number;
    clientWidth?: number;
    activeAnimationCount?: number;
  };
  screenshotPath: string | null;
};

type HomepageHeroUiProofReport = {
  schemaVersion: "ui-proof-report.v1";
  proofType: "witnessops.web.homepage-hero.mobile";
  status: ReportStatus;
  repo: "witnessops/witnessops-web";
  route: "/";
  generatedAt: string;
  commitSha: string;
  browser: "chromium";
  asset: {
    assetId: string;
    src: string;
    width: number;
    height: number;
    sourcePath?: string;
    sourceRecord?: string;
    sourceStatus?: string;
    sourceCommit?: string;
    sourceSha256?: string;
  };
  artifacts: {
    report: string;
    grid: string;
    screenshotsDir: string;
  };
  scenarios: ScenarioResult[];
};

const reportPublicPath = "/ui-proofs/homepage-hero/latest.json";
const gridPublicPath = "/ui-proofs/homepage-hero/grid.png";

export const metadata: Metadata = {
  title: "Homepage Hero UI Proof | WitnessOps",
  description:
    "A noindex presentation page for the committed homepage hero mobile UI proof report.",
  robots: {
    index: false,
    follow: false,
  },
};

export default function VerifyUiPage() {
  const report = readReport();
  const grid = readPublicPngDimensions(gridPublicPath);
  const summary = summarizeScenarios(report.scenarios);

  return (
    <main id="main-content" tabIndex={-1}>
      <SectionShell>
        <div className="grid gap-8 lg:grid-cols-[1.05fr,0.95fr] lg:items-start">
          <div>
            <p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-brand-accent">
              UI proof report
            </p>
            <h1 className="text-4xl font-bold tracking-tight text-text-primary lg:text-5xl">
              Homepage hero mobile proof snapshot.
            </h1>
            <p className="mt-5 max-w-[50rem] text-base leading-8 text-text-secondary">
              This page presents the committed V1 UI proof report for the homepage
              hero underlay. It shows the scenario results, the tested asset
              metadata, and the screenshot grid generated by the Playwright UI
              proof runner.
            </p>
            <p className="mt-4 max-w-[50rem] text-sm leading-7 text-text-muted">
              This is a presentation surface for a committed UI proof report.
              It does not extend the report beyond the homepage hero UI proof
              checks, and it is not a deployment, release, or broader product
              assurance claim.
            </p>
            <div className="mt-6 flex flex-wrap gap-3">
              <CtaButton href={reportPublicPath} variant="primary" label="View raw JSON" />
              <CtaButton href={gridPublicPath} variant="secondary" label="Open screenshot grid" />
            </div>
          </div>
          <div className="border border-surface-border bg-surface-bg p-5">
            <div className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-brand-accent">
              Report status
            </div>
            <dl className="grid gap-3 text-sm">
              <ReportFact label="Status" value={report.status} emphasize />
              <ReportFact label="Proof type" value={report.proofType} />
              <ReportFact label="Schema" value={report.schemaVersion} />
              <ReportFact label="Route tested" value={report.route} />
              <ReportFact label="Browser" value={report.browser} />
              <ReportFact label="Generated" value={formatIso(report.generatedAt)} />
              <ReportFact label="Commit tested" value={report.commitSha} mono />
            </dl>
          </div>
        </div>
      </SectionShell>
      <SectionShell className="pt-0">
        <div className="grid gap-4 md:grid-cols-4">
          <SummaryCard label="Passed" value={summary.pass} />
          <SummaryCard label="Warnings" value={summary.warn} />
          <SummaryCard label="Failures" value={summary.fail} />
          <SummaryCard label="Scenarios" value={report.scenarios.length} />
        </div>
      </SectionShell>
      <SectionShell className="pt-0">
        <div className="border border-surface-border bg-surface-bg p-6">
          <div className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-brand-accent">
            Context boundaries
          </div>
          <div className="grid gap-3 md:grid-cols-4">
            <BoundaryCard
              title="CI logs"
              body="Execution evidence from the workflow or local run."
            />
            <BoundaryCard
              title="UI report"
              body="Verification result for the V1 homepage hero UI proof checks."
            />
            <BoundaryCard
              title="Asset metadata"
              body="Catalog context for the Asset Foundry homepage hero visual."
            />
            <BoundaryCard
              title="/verify-ui"
              body="Presentation context for the committed report and grid."
            />
          </div>
        </div>
      </SectionShell>
      <SectionShell className="pt-0">
        <div className="border border-surface-border bg-surface-bg p-6">
          <div className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-brand-accent">
            Asset catalog context
          </div>
          <dl className="grid gap-3 text-sm md:grid-cols-2">
            <ReportFact label="Asset ID" value={report.asset.assetId} />
            <ReportFact label="Asset source" value={report.asset.src} mono />
            <ReportFact
              label="Source commit"
              value={report.asset.sourceCommit ?? "not recorded"}
              mono
            />
            <ReportFact
              label="Source SHA-256"
              value={report.asset.sourceSha256 ?? "not recorded"}
              mono
            />
            <ReportFact
              label="Asset dimensions"
              value={`${report.asset.width}x${report.asset.height}`}
            />
            <ReportFact
              label="Source status"
              value={report.asset.sourceStatus ?? "not recorded"}
            />
          </dl>
        </div>
      </SectionShell>
      <SectionShell className="pt-0">
        <div className="border border-surface-border bg-surface-bg p-6">
          <div className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-brand-accent">
            Scenario summary
          </div>
          <div className="overflow-x-auto">
            <table className="w-full min-w-[760px] border-collapse text-left text-sm">
              <thead>
                <tr className="border-b border-surface-border text-xs uppercase tracking-[0.12em] text-text-muted">
                  <th className="py-3 pr-4 font-semibold">Scenario</th>
                  <th className="py-3 pr-4 font-semibold">Severity</th>
                  <th className="py-3 pr-4 font-semibold">Status</th>
                  <th className="py-3 pr-4 font-semibold">Viewport</th>
                  <th className="py-3 pr-4 font-semibold">Motion</th>
                  <th className="py-3 pr-4 font-semibold">Failed checks</th>
                </tr>
              </thead>
              <tbody>
                {report.scenarios.map((scenario) => {
                  const failedChecks = scenario.checks.filter(
                    (check) => check.status === "fail",
                  );
                  return (
                    <tr key={scenario.scenario.name} className="border-b border-surface-border">
                      <td className="py-3 pr-4 font-mono text-xs text-text-primary">
                        {scenario.scenario.name}
                      </td>
                      <td className="py-3 pr-4 text-text-muted">
                        {scenario.scenario.severity}
                      </td>
                      <td className="py-3 pr-4">
                        <StatusPill status={scenario.status} />
                      </td>
                      <td className="py-3 pr-4 text-text-muted">
                        {scenario.scenario.viewport.width}x{scenario.scenario.viewport.height}
                      </td>
                      <td className="py-3 pr-4 text-text-muted">
                        {scenario.scenario.reducedMotion}
                      </td>
                      <td className="py-3 pr-4 text-text-muted">
                        {failedChecks.length > 0
                          ? failedChecks.map((check) => check.name).join(", ")
                          : "None"}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </SectionShell>
      <SectionShell className="pt-0">
        <div className="border border-surface-border bg-surface-bg p-6">
          <div className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-brand-accent">
            Screenshot grid
          </div>
          <p className="mb-5 max-w-[48rem] text-sm leading-7 text-text-muted">
            The grid is a committed image generated from the mobile scenario
            screenshots. Use it as visual context alongside the semantic checks
            in the report.
          </p>
          <a
            href={gridPublicPath}
            className="block overflow-hidden border border-surface-border bg-surface-card"
          >
            <Image
              src={gridPublicPath}
              alt="Homepage hero UI proof screenshot grid"
              width={grid.width}
              height={grid.height}
              className="h-auto w-full"
              priority={false}
            />
          </a>
        </div>
      </SectionShell>
    </main>
  );
}

function readReport(): HomepageHeroUiProofReport {
  const filePath = path.join(
    process.cwd(),
    "public",
    "ui-proofs",
    "homepage-hero",
    "latest.json",
  );
  return JSON.parse(readFileSync(filePath, "utf8")) as HomepageHeroUiProofReport;
}

function readPublicPngDimensions(publicPath: string) {
  const normalizedPath = publicPath.replace(/^\/+/, "");
  const filePath = path.join(process.cwd(), "public", normalizedPath);
  const buffer = readFileSync(filePath);
  return {
    width: buffer.readUInt32BE(16),
    height: buffer.readUInt32BE(20),
  };
}

function summarizeScenarios(scenarios: ScenarioResult[]) {
  return scenarios.reduce(
    (summary, scenario) => ({
      ...summary,
      [scenario.status]: summary[scenario.status] + 1,
    }),
    { pass: 0, warn: 0, fail: 0 } satisfies Record<ScenarioStatus, number>,
  );
}

function formatIso(value: string) {
  return new Date(value).toISOString();
}

function SummaryCard({ label, value }: { label: string; value: number }) {
  return (
    <div className="border border-surface-border bg-surface-bg p-5">
      <div className="text-xs font-semibold uppercase tracking-[0.16em] text-text-muted">
        {label}
      </div>
      <div className="mt-3 text-3xl font-semibold text-text-primary">{value}</div>
    </div>
  );
}

function BoundaryCard({ title, body }: { title: string; body: string }) {
  return (
    <div className="border border-surface-border bg-surface-card p-4">
      <h2 className="text-sm font-semibold uppercase tracking-[0.08em] text-text-primary">
        {title}
      </h2>
      <p className="mt-2 text-sm leading-relaxed text-text-muted">{body}</p>
    </div>
  );
}

function ReportFact({
  label,
  value,
  mono,
  emphasize,
}: {
  label: string;
  value: string;
  mono?: boolean;
  emphasize?: boolean;
}) {
  return (
    <div className="border border-surface-border bg-surface-card p-4">
      <dt className="text-xs font-semibold uppercase tracking-[0.14em] text-text-muted">
        {label}
      </dt>
      <dd
        className={`mt-2 break-all ${
          mono ? "font-mono text-xs" : "text-sm"
        } ${emphasize ? "font-semibold uppercase text-text-primary" : "text-text-primary"}`}
      >
        {value}
      </dd>
    </div>
  );
}

function StatusPill({ status }: { status: ScenarioStatus | ReportStatus }) {
  const label =
    status === "pass" ? "Pass" : status === "warn" ? "Warn" : "Fail";
  return (
    <span className="inline-flex border border-surface-border bg-surface-card px-2 py-1 text-xs font-semibold uppercase tracking-[0.12em] text-text-primary">
      {label}
    </span>
  );
}
