apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: witnessops
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: witnessops-web
    newName: ghcr.io/witnessops/witnessops-web
    newTag: replace-me