apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${INTAKE_STORE_PVC}
  namespace: ${DEPLOY_NS}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${INTAKE_EVENTS_PVC}
  namespace: ${DEPLOY_NS}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${MAIL_OUT_PVC}
  namespace: ${DEPLOY_NS}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
