apiVersion: v1
kind: Service
metadata:
  name: ${PROD_SERVICE}
  namespace: ${DEPLOY_NS}
  labels:
    app: ${PROD_DEPLOY}
spec:
  type: ClusterIP
  selector:
    app: ${PROD_DEPLOY}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
