import "server-only";

import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";

import type { AskRuntimeReceipt } from "./ask-runtime-receipt";

/**
 * WITNESSOPS_ASK_RUNTIME_RECEIPT_DURABLE_CUSTODY_V1
 *
 * Simple file-based durable store for Ask runtime receipts.
 *
 * Guarantees (V1):
 * - Atomic writes via temp file + rename + fsync
 * - Immutable: once written, the file is never overwritten
 * - Content hash verification on write and on read
 * - Explicit failure on any write error (no silent success)
 *
 * Storage layout (configurable root):
 *   <root>/<receipt_id>.json
 *
 * Access control in V1: internal to the server process only.
 * Later lanes can add authenticated retrieval.
 */

export interface ReceiptWriteResult {
  readonly ok: true;
  readonly receiptId: string;
  readonly path: string;
}

export interface ReceiptWriteError {
  readonly ok: false;
  readonly reason: string;
}

export interface ReceiptReadResult {
  readonly ok: true;
  readonly receipt: AskRuntimeReceipt;
  readonly path: string;
}

export interface ReceiptReadError {
  readonly ok: false;
  readonly reason: string;
}

const DEFAULT_RECEIPT_ROOT = path.resolve(
  process.env.ASK_RECEIPT_ROOT || "/var/lib/witnessops/ask-receipts"
);

function ensureDir(dir: string): void {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  }
}

function receiptPath(receiptId: string, root: string = DEFAULT_RECEIPT_ROOT): string {
  // Basic sanitization: receipt IDs are generated by us, but be defensive
  const safeId = receiptId.replace(/[^a-zA-Z0-9_.-]/g, "_");
  return path.join(root, `${safeId}.json`);
}

function computeContentHash(obj: unknown): string {
  const canonical = JSON.stringify(obj, Object.keys(obj as object).sort());
  return createHash("sha256").update(canonical).digest("hex");
}

export async function writeReceipt(
  receipt: AskRuntimeReceipt,
  root: string = DEFAULT_RECEIPT_ROOT
): Promise<ReceiptWriteResult | ReceiptWriteError> {
  ensureDir(root);

  const targetPath = receiptPath(receipt.receipt_id, root);
  const tempPath = `${targetPath}.tmp.${process.pid}.${Date.now()}`;

  try {
    // Verify the receipt has the expected schema and required fields
    if (receipt.schema !== "witnessops.ask.runtime-receipt.v1") {
      return { ok: false, reason: "INVALID_RECEIPT_SCHEMA" };
    }

    const expectedHash = receipt.deterministic_replay_hash;
    const computedHash = computeContentHash({
      ...receipt,
      deterministic_replay_hash: undefined, // exclude the hash field itself for content hash
    });

    // For V1 we store the receipt as-is and also record a content hash for integrity
    const payload = {
      ...receipt,
      _content_hash: computedHash, // internal integrity marker
    };

    const data = JSON.stringify(payload, null, 2);

    // Atomic write: write to temp, fsync, rename
    await fs.promises.writeFile(tempPath, data, { mode: 0o600 });
    const fd = await fs.promises.open(tempPath, "r+");
    await fd.sync();
    await fd.close();

    // Verify what we just wrote
    const written = await fs.promises.readFile(tempPath, "utf8");
    const writtenObj = JSON.parse(written);
    if (writtenObj._content_hash !== computedHash) {
      await fs.promises.unlink(tempPath).catch(() => {});
      return { ok: false, reason: "WRITE_VERIFICATION_FAILED" };
    }

    // Atomic rename (will fail if target already exists — good for immutability)
    try {
      await fs.promises.rename(tempPath, targetPath);
    } catch (renameErr: any) {
      await fs.promises.unlink(tempPath).catch(() => {});
      if (renameErr.code === "EEXIST") {
        return { ok: false, reason: "RECEIPT_ALREADY_EXISTS" };
      }
      throw renameErr;
    }

    return { ok: true, receiptId: receipt.receipt_id, path: targetPath };
  } catch (err: any) {
    await fs.promises.unlink(tempPath).catch(() => {});
    return { ok: false, reason: `WRITE_FAILED: ${err.message}` };
  }
}

export async function readReceipt(
  receiptId: string,
  root: string = DEFAULT_RECEIPT_ROOT
): Promise<ReceiptReadResult | ReceiptReadError> {
  const filePath = receiptPath(receiptId, root);

  try {
    const data = await fs.promises.readFile(filePath, "utf8");
    const receipt: AskRuntimeReceipt & { _content_hash?: string } = JSON.parse(data);

    if (receipt.schema !== "witnessops.ask.runtime-receipt.v1") {
      return { ok: false, reason: "INVALID_RECEIPT_SCHEMA" };
    }

    // Verify internal content hash if present
    if (receipt._content_hash) {
      const { _content_hash, ...rest } = receipt;
      const recomputed = computeContentHash(rest);
      if (recomputed !== _content_hash) {
        return { ok: false, reason: "CONTENT_HASH_MISMATCH" };
      }
    }

    // Remove internal marker before returning
    const { _content_hash, ...cleanReceipt } = receipt;

    return {
      ok: true,
      receipt: cleanReceipt as AskRuntimeReceipt,
      path: filePath,
    };
  } catch (err: any) {
    if (err.code === "ENOENT") {
      return { ok: false, reason: "RECEIPT_NOT_FOUND" };
    }
    return { ok: false, reason: `READ_FAILED: ${err.message}` };
  }
}

export function getReceiptRoot(): string {
  return DEFAULT_RECEIPT_ROOT;
}
