import "server-only";

import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";

import type { AskRuntimeReceipt } from "./ask-runtime-receipt";
import { withFilesystemLock } from "../filesystem-lock";

/**
 * WITNESSOPS_ASK_RUNTIME_RECEIPT_DURABLE_CUSTODY_V1
 *
 * Simple file-based durable store for Ask runtime receipts.
 *
 * Guarantees (V1):
 * - Atomic writes via temp file + rename + fsync
 * - Immutable: once written, the file is never overwritten
 * - Content hash verification on write and on read
 * - Explicit failure on any write error (no silent success)
 *
 * Storage layout (configurable root):
 *   <root>/<receipt_id>.json
 *
 * Access control in V1: internal to the server process only.
 * Later lanes can add authenticated retrieval.
 */

export interface ReceiptWriteResult {
  readonly ok: true;
  readonly receiptId: string;
  readonly path: string;
}

export interface ReceiptWriteError {
  readonly ok: false;
  readonly reason: string;
}

export interface ReceiptReadResult {
  readonly ok: true;
  readonly receipt: AskRuntimeReceipt;
  readonly path: string;
}

export interface ReceiptReadError {
  readonly ok: false;
  readonly reason: string;
}

const DEFAULT_RECEIPT_ROOT = path.resolve(
  process.env.ASK_RECEIPT_ROOT ||
    path.join(process.cwd(), ".witnessops-token-store", "ask-receipts"),
);

export interface ReceiptStorageLimits {
  readonly maxFiles: number;
  readonly maxBytes: number;
  readonly minFreeBytes: number;
}

const DEFAULT_MAX_FILES = 10_000;
const DEFAULT_MAX_BYTES = 256 * 1024 * 1024;
const DEFAULT_MIN_FREE_BYTES = 128 * 1024 * 1024;

function positiveInteger(value: string | undefined, fallback: number): number {
  if (!value || !/^\d+$/.test(value)) return fallback;
  const parsed = Number(value);
  return Number.isSafeInteger(parsed) && parsed > 0 ? parsed : fallback;
}

function configuredStorageLimits(): ReceiptStorageLimits {
  return {
    maxFiles: positiveInteger(
      process.env.WITNESSOPS_ASK_RECEIPT_MAX_FILES,
      DEFAULT_MAX_FILES,
    ),
    maxBytes: positiveInteger(
      process.env.WITNESSOPS_ASK_RECEIPT_MAX_BYTES,
      DEFAULT_MAX_BYTES,
    ),
    minFreeBytes: positiveInteger(
      process.env.WITNESSOPS_ASK_RECEIPT_MIN_FREE_BYTES,
      DEFAULT_MIN_FREE_BYTES,
    ),
  };
}

function ensureDir(dir: string): void {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  }
}

function receiptPath(receiptId: string, root: string = DEFAULT_RECEIPT_ROOT): string {
  // Basic sanitization: receipt IDs are generated by us, but be defensive
  const safeId = receiptId.replace(/[^a-zA-Z0-9_.-]/g, "_");
  return path.join(root, `${safeId}.json`);
}

function computeContentHash(obj: unknown): string {
  const canonical = JSON.stringify(obj, Object.keys(obj as object).sort());
  return createHash("sha256").update(canonical).digest("hex");
}

function errorCode(error: unknown): string | undefined {
  if (!error || typeof error !== "object" || !("code" in error)) return undefined;
  return typeof error.code === "string" ? error.code : undefined;
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export async function writeReceipt(
  receipt: AskRuntimeReceipt,
  root: string = DEFAULT_RECEIPT_ROOT,
  limits: ReceiptStorageLimits = configuredStorageLimits(),
): Promise<ReceiptWriteResult | ReceiptWriteError> {
  const targetPath = receiptPath(receipt.receipt_id, root);

  try {
    ensureDir(root);

    // Verify the receipt has the expected schema and required fields
    if (receipt.schema !== "witnessops.ask.runtime-receipt.v1") {
      return { ok: false, reason: "INVALID_RECEIPT_SCHEMA" };
    }

    return await withFilesystemLock(
      {
        lockPath: path.join(root, ".receipt-store.lock"),
        description: "Ask receipt storage admission",
      },
      async () => {
        const computedHash = computeContentHash(receipt);
        const payload = { ...receipt, _content_hash: computedHash };
        const data = JSON.stringify(payload, null, 2);
        const dataBytes = Buffer.byteLength(data);
        const receiptFiles = (await fs.promises.readdir(root, { withFileTypes: true }))
          .filter((entry) => entry.isFile() && entry.name.endsWith(".json"));

        if (receiptFiles.length >= limits.maxFiles) {
          return { ok: false, reason: "CAPACITY_FILE_LIMIT" };
        }

        const sizes = await Promise.all(
          receiptFiles.map(async (entry) =>
            (await fs.promises.stat(path.join(root, entry.name))).size,
          ),
        );
        if (sizes.reduce((total, size) => total + size, 0) + dataBytes > limits.maxBytes) {
          return { ok: false, reason: "CAPACITY_BYTE_LIMIT" };
        }

        const filesystem = await fs.promises.statfs(root);
        const freeBytes = Number(filesystem.bavail) * Number(filesystem.bsize);
        if (!Number.isFinite(freeBytes) || freeBytes - dataBytes < limits.minFreeBytes) {
          return { ok: false, reason: "CAPACITY_LOW_SPACE" };
        }

        const tempPath = `${targetPath}.tmp.${process.pid}.${Date.now()}`;
        try {
          await fs.promises.writeFile(tempPath, data, { mode: 0o600 });
          const fd = await fs.promises.open(tempPath, "r+");
          try {
            await fd.sync();
          } finally {
            await fd.close();
          }

          const written = await fs.promises.readFile(tempPath, "utf8");
          const writtenObj = JSON.parse(written) as { _content_hash?: unknown };
          if (writtenObj._content_hash !== computedHash) {
            return { ok: false, reason: "WRITE_VERIFICATION_FAILED" };
          }

          try {
            await fs.promises.rename(tempPath, targetPath);
          } catch (renameError: unknown) {
            if (errorCode(renameError) === "EEXIST") {
              return { ok: false, reason: "RECEIPT_ALREADY_EXISTS" };
            }
            throw renameError;
          }

          return { ok: true, receiptId: receipt.receipt_id, path: targetPath };
        } finally {
          await fs.promises.unlink(tempPath).catch(() => {});
        }
      }
    );
  } catch (error: unknown) {
    return { ok: false, reason: `WRITE_FAILED: ${errorMessage(error)}` };
  }
}

export async function readReceipt(
  receiptId: string,
  root: string = DEFAULT_RECEIPT_ROOT
): Promise<ReceiptReadResult | ReceiptReadError> {
  const filePath = receiptPath(receiptId, root);

  try {
    const data = await fs.promises.readFile(filePath, "utf8");
    const receipt: AskRuntimeReceipt & { _content_hash?: string } = JSON.parse(data);

    if (receipt.schema !== "witnessops.ask.runtime-receipt.v1") {
      return { ok: false, reason: "INVALID_RECEIPT_SCHEMA" };
    }

    // Verify internal content hash if present
    if (receipt._content_hash) {
      const { _content_hash, ...rest } = receipt;
      const recomputed = computeContentHash(rest);
      if (recomputed !== _content_hash) {
        return { ok: false, reason: "CONTENT_HASH_MISMATCH" };
      }
    }

    // Remove internal marker before returning
    const { _content_hash, ...cleanReceipt } = receipt;

    return {
      ok: true,
      receipt: cleanReceipt as AskRuntimeReceipt,
      path: filePath,
    };
  } catch (error: unknown) {
    if (errorCode(error) === "ENOENT") {
      return { ok: false, reason: "RECEIPT_NOT_FOUND" };
    }
    return { ok: false, reason: `READ_FAILED: ${errorMessage(error)}` };
  }
}

export function getReceiptRoot(): string {
  return DEFAULT_RECEIPT_ROOT;
}
