import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { RECOMMENDED_PROFILE, type Run, type Workspace } from '../../apps/witnessops-app/src/lib/model';
import { canonicalSource } from '../../apps/witnessops-app/src/lib/source-digest';
const source=JSON.parse(readFileSync(resolve('tests/external-exposure/fixtures/public-witnessops-snapshot-20260910.json'),'utf8'));
for(const width of [390,1440]) for(const role of ['owner','viewer'] as const) test(`finding-led actions ${role} ${width}`,async({page},info)=>{
 const snapshot=structuredClone(source),check=snapshot.checks.find((c:{check_id:string})=>c.check_id==='web.hsts.v1');
 check.status='NEEDS_ATTENTION';check.interpretation='Recorded fixture interpretation.';check.recommendation='Review the HTTPS response configuration.';
 const run:Run={id:'run-actions',assetId:'asset-actions',createdAt:snapshot.finished_at,profile:structuredClone(RECOMMENDED_PROFILE),snapshot,sourceDigest:createHash('sha256').update(canonicalSource(snapshot)).digest('hex')};
 const ws:Workspace={id:'workspace-actions',name:'Private workspace',slug:'actions',role,members:[],assets:[{id:run.assetId,hostname:snapshot.target,type:'hostname',createdAt:run.createdAt}],runs:[run]};
 const writes:string[]=[];
 await page.setViewportSize({width,height:900});
 await page.route('**/api/**',route=>{const path=new URL(route.request().url()).pathname;
 if(path==='/api/workspace')return route.fulfill({json:{user:{id:'user'},workspaces:[ws],workspace:ws}});
 if(path==='/api/events')return route.fulfill({json:{recorded:true}});
 if(path==='/api/feedback')return route.fulfill({json:[]});
 writes.push(path);return route.abort();});
 await page.goto(`/reports/${run.id}`);
 const article=page.locator('main article'),summary=article.getByRole('region',{name:'What to do next'});
 await expect(summary).toContainText(check.recommendation);await expect(summary).toContainText('Severity not assessed');
 await summary.getByRole('link',{name:'Inspect finding'}).first().click();
 const finding=article.locator('section[id^="report-finding-"]').filter({has:page.getByRole('heading',{name:check.title,exact:true})});
 await expect(finding).toContainText('What remains unproved');await expect(finding).toContainText('An appropriate follow-up test still needs to be agreed.');
 await expect(finding.getByRole('link',{name:'Inspect evidence'})).toHaveAttribute('href',`/runs/${run.id}/observations/${check.check_id}`);
 if(role==='owner')await expect(finding.getByRole('link',{name:'Check again'})).toHaveAttribute('href',`/assets/${run.assetId}#run-observation`);else await expect(finding.getByRole('link',{name:'Check again'})).toHaveCount(0);
 const ask=finding.getByRole('button',{name:'Ask about this finding'});await ask.focus();await page.keyboard.press('Enter');
 const draft=finding.getByRole('region',{name:'Finding help request'});await expect(draft.getByLabel('Finding title')).toBeFocused();
 await expect(draft.getByLabel('Request preview')).not.toContainText(snapshot.target);
 await draft.getByLabel('What I need to establish').fill('What should we check before handover?');
 const mail=draft.getByRole('link',{name:'Open email draft'});expect(decodeURIComponent((await mail.getAttribute('href'))!)).toContain('What should we check before handover?');
 await draft.getByRole('checkbox').check();await expect(draft.getByLabel('Request preview')).toContainText(`Target (included by you): ${snapshot.target}`);
 await draft.getByRole('checkbox').uncheck();
 await page.evaluate(()=>Object.defineProperty(navigator.clipboard,'writeText',{configurable:true,value:async(text:string)=>{(window as Window & {copied?:string}).copied=text;}}));
 await draft.getByRole('button',{name:'Copy request'}).click();expect(await page.evaluate(()=>(window as Window & {copied?:string}).copied)).not.toContain(snapshot.target);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
 await page.screenshot({path:info.outputPath(`finding-draft-${role}-${width}.png`)});
 await page.emulateMedia({media:'print'});const print=page.locator('[data-buyer-print-root]');await expect(print).toContainText(check.recommendation);await expect(print.getByRole('region',{name:'Finding help request'})).toHaveCount(0);await expect(print.getByRole('button')).toHaveCount(0);await page.emulateMedia({media:'screen'});
 await draft.getByRole('button',{name:'Cancel draft'}).click();await expect(ask).toBeFocused();await expect(draft).toHaveCount(0);
 await ask.click();await draft.getByLabel('What I need to establish').fill('Discard me');await page.keyboard.press('Escape');await expect(ask).toBeFocused();await expect(draft).toHaveCount(0);
 if(role==='owner'){await finding.getByRole('link',{name:'Check again'}).click();await expect(page.getByRole('checkbox',{name:'I own this hostname or am authorized to check it.'})).not.toBeChecked();await expect(page.getByRole('button',{name:'Run again',exact:true})).toBeDisabled();await page.goto(`/reports/${run.id}`);}
 await finding.getByRole('link',{name:'Inspect evidence'}).click();await expect(page).toHaveURL(new RegExp(`/observations/${check.check_id}$`));
 expect(writes).toEqual([]);
});

import { verifyProofpack } from '../../apps/witnessops-web/src/lib/proofpack/verify.mjs';
import { pinnedRegistryInput } from '../../apps/witnessops-web/src/lib/proofpack/pinned-registry';
import { localAuditAdapter } from '../../apps/witnessops-web/src/lib/proofpack/local-audit-adapter';
import type { LinuxCheckRun } from '../../apps/witnessops-app/src/lib/model';
for(const role of ['owner','viewer'] as const) test(`Linux finding actions ${role}`,async({page},info)=>{
 const name='proofpack-pr_lsa_20260710120000_198fd7aceb.zip',path=resolve('tests/proofpack/production-fixtures/adverse',name);
 const checked=await verifyProofpack({proofpack:{name,bytes:readFileSync(path)},signature:{name:name+'.sig.json',bytes:readFileSync(path+'.sig.json')},trust_registry:pinnedRegistryInput()});
 const model=localAuditAdapter(checked,'2026-09-18T12:00:00Z')!;expect(model).toBeTruthy();
 const run:LinuxCheckRun={id:'linux-run',assetId:'linux-asset',createdAt:model.identity.generatedAt,sourceDigest:model.identity.sourceDigest,proofRunId:checked.proof_run_id,verifierVersion:checked.verifier_version,profileId:'linux_baseline_v1',outcome:checked.outcome,synthetic:true,observedHostname:model.subject.label,observedAt:model.subject.observedAt,sourceAssetId:'asset-demo-host-001',machineIdentity:null};
 const ws:Workspace={id:'linux-workspace',name:'Private Linux',slug:'linux',role,assets:[{id:run.assetId,hostname:model.subject.label,type:'linux_server',createdAt:run.createdAt}],runs:[],linuxRuns:[run],members:[]};
 const writes:string[]=[];await page.setViewportSize({width:390,height:900});
 await page.route('**/api/**',route=>{const path=new URL(route.request().url()).pathname;
 if(path==='/api/workspace')return route.fulfill({json:{user:{id:'user'},workspaces:[ws],workspace:ws}});
 if(path==='/api/linux-checks' && route.request().method()==='GET')return route.fulfill({json:{run,model}});
 if(path==='/api/feedback')return route.fulfill({json:[]});
 if(path==='/api/events')return route.fulfill({json:{recorded:true}});
 writes.push(path);return route.abort();});
 await page.goto(`/reports/${run.id}`);const article=page.locator('main article');await expect(article).toContainText('What to do next');
 const finding=article.locator('section[id^="report-finding-"]').first();await expect(finding).toBeVisible();
 await finding.getByRole('link',{name:'Inspect evidence'}).click();await expect(page).toHaveURL(/#report-evidence-\d+$/);
 if(role==='owner')await expect(finding.getByRole('link',{name:'Open fresh-result / import steps'})).toHaveAttribute('href',`/assets/${run.assetId}`);else await expect(finding.getByRole('link',{name:'Open fresh-result / import steps'})).toHaveCount(0);
 await finding.getByRole('button',{name:'Ask about this finding'}).click();const draft=finding.getByRole('region',{name:'Finding help request'});await expect(draft.getByLabel('Request preview')).not.toContainText(model.subject.label);
 await expect(article).toContainText(model.findings[0].limitations[0]);await page.screenshot({path:info.outputPath(`linux-actions-${role}.png`)});expect(writes).toEqual([]);
});
