'use client';
import { useEffect,useRef,useState } from 'react';
type State={enabled:boolean;sandbox:boolean;canManage?:boolean;status?:string;cancelAtPeriodEnd?:boolean;hasCustomer?:boolean;entitlement?:{source:string;seats:number;expiresAt?:string};plans?:{key:string;name:string;amount:number;currency:string;interval:string;seats:number}[]};
export function Billing({workspaceId}:{workspaceId:string}){
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false),generation=useRef(0);
 async function request(action?:string,plan?:string){const response=await fetch('/api/billing',{method:action?'POST':'GET',cache:'no-store',headers:{'X-WitnessOps-Workspace':workspaceId,...(action?{'Content-Type':'application/json'}:{})},...(action?{body:JSON.stringify({action,...(plan?{plan}:{})})}:{})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Billing unavailable.');return result;}
 useEffect(()=>{const current=++generation.current;lock.current=false;setBusy(false);let active=true;setState(null);setError('');void request().then(value=>{if(active)setState(value);}).catch(()=>{if(active)setError('Billing is unavailable. Your saved work remains available.');});return()=>{active=false;if(generation.current===current)generation.current++;};},[workspaceId]); // eslint-disable-line react-hooks/exhaustive-deps
 async function act(action:string,plan?:string){if(lock.current)return;const current=generation.current;const active=()=>generation.current===current;lock.current=true;setBusy(true);setError('');try{let result=await request(action,plan);if(!active())return;if(result.retry)result=await request(action,plan);if(!active())return;if(result.url){const url=new URL(result.url);if(url.protocol!=='https:'||!['checkout.stripe.com','billing.stripe.com'].includes(url.hostname))throw new Error('Unexpected billing destination.');window.location.assign(url.href);return;}else {const next=await request();if(active())setState(next);}}catch(cause){if(active())setError(cause instanceof Error?cause.message:'Billing unavailable.');}finally{if(active()){lock.current=false;setBusy(false);}}}
 return <section className="section billing-panel" aria-label="Workspace billing"><h2>Workspace billing</h2>{error&&<p role="alert" className="error">{error}</p>}{!state&&!error?<p role="status">Loading billing…</p>:state?.enabled?<><p className="eyebrow">Stripe sandbox · test payments only</p><p><strong>{state.entitlement?.seats} included {state.entitlement?.seats===1?'seat':'seats'}</strong> · {state.entitlement?.source} · {state.status}</p>{state.cancelAtPeriodEnd&&<p>Cancellation is scheduled. Paid seats remain available until the paid period ends.</p>}{state.entitlement?.expiresAt&&<p>Current entitlement ends {new Date(state.entitlement.expiresAt).toLocaleString()}.</p>}<p>Comparison, Share, Linux imports and exports remain available on free workspaces. Payment does not authorize a check.</p><p>After a downgrade, existing members and evidence remain. New invitations and acceptance must fit the current seat allowance; pending invitations reserve seats.</p>{state.canManage?<><div className="actions"><button className="button secondary" disabled={busy} onClick={()=>void act('refresh')}>Refresh billing status</button>{state.hasCustomer&&<button className="button secondary" disabled={busy} onClick={()=>void act('portal')}>Manage billing</button>}</div>{state.entitlement?.source!=='complimentary'&&state.status==='free'&&<div className="billing-plans">{state.plans?.map(plan=><div className="member-row" key={plan.key}><div><strong>{plan.name}</strong><p>{plan.seats} seats · {new Intl.NumberFormat(undefined,{style:'currency',currency:plan.currency}).format(plan.amount/100)}/{plan.interval} · sandbox</p></div><button className="button" disabled={busy} onClick={()=>void act('checkout',plan.key)}>Choose {plan.name}</button></div>)}</div>}</>:<p>An Owner manages billing for this workspace.</p>}<p className="quiet">Returning from Checkout does not grant seats. Billing status changes only after server reconciliation.</p></>:state?<p>Paid billing is not enabled. Creating an account requires no card.</p>:null}</section>;
}
