'use client';
import { useEffect, useRef, useState } from 'react';
import type { WorkspaceRole } from '../lib/workspace-role-policy';
type Member = { id:string;displayName:string|null;role:WorkspaceRole;generation:number };
type Invite = { id:string;recipient:string;role:WorkspaceRole;revision:number;state:string;expiresAt:string;deliveryState:string;provider:string|null };
type State = { members:Member[];invitations:Invite[];role:WorkspaceRole };
const roles=['viewer','contributor','owner'] as const;
const label=(value:string)=>value[0].toUpperCase()+value.slice(1);
export function Members({workspaceId,onChanged}:{workspaceId:string;onChanged:()=>Promise<void>}) {
 const [data,setData]=useState<State|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[role,setRole]=useState<WorkspaceRole>('viewer'),[key,setKey]=useState('');
 const [inviteOpen,setInviteOpen]=useState(false);
 const emailInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(inviteOpen)emailInput.current?.focus();},[inviteOpen]);
 const [confirm,setConfirm]=useState<{member:Member;role:WorkspaceRole|null}|null>(null);
 async function load(body?:unknown) {
  const response=await fetch('/api/members',{method:body?'POST':'GET',headers:{'X-WitnessOps-Workspace':workspaceId,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});
  const value=await response.json();if(!response.ok)throw new Error(value.error||'Could not load members.');setData(value.removed?null:value);
 }
 useEffect(()=>{let active=true;fetch('/api/members',{headers:{'X-WitnessOps-Workspace':workspaceId}}).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error);if(active)setData(value);}).catch(cause=>{if(active)setError(cause.message);});return()=>{active=false;};},[workspaceId]);
 async function act(body:unknown) {if(busy)return;setBusy(true);setError('');try{await load(body);setConfirm(null);await onChanged();}catch(cause){setError(cause instanceof Error?cause.message:'Request failed.');await onChanged().catch(()=>undefined);}finally{setBusy(false);}}
 return <section className="members-page"><div className="page-heading"><div><h1>Members</h1><p className="support">People and access in this workspace.</p></div>{data?.role==='owner'&&<button className="button" aria-expanded={inviteOpen} aria-controls="invite-teammate" onClick={()=>setInviteOpen(!inviteOpen)}>Invite teammate</button>}</div>{error&&<p role="alert" className="error">{error}</p>}{!data?<p role="status">Loading members…</p>:<>
 <div className="members-list" aria-label="Workspace members">{data.members.map(member=><div className="member-row" key={member.id}><strong>{member.displayName||'Workspace member'}</strong><span className="member-role">{label(member.role)}</span>{data.role==='owner'&&<div className="actions"><label>Role for {member.displayName||'member'}<select value={member.role} disabled={busy} onChange={event=>setConfirm({member,role:event.target.value as WorkspaceRole})}>{roles.map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label><button className="button secondary" disabled={busy} onClick={()=>setConfirm({member,role:null})}>Remove {member.displayName||'member'}</button></div>}</div>)}</div>
 {confirm&&<section className="empty compact" role="region" aria-label="Confirm membership change"><h2>{confirm.role?'Change role':'Remove member'}?</h2><p>{confirm.role?`Set ${confirm.member.displayName||'this member'} to ${label(confirm.role)}.`:'Remove this person’s workspace access.'} Existing CLI authority will stop working. The last active Owner cannot be removed or demoted.</p><div className="actions"><button className="button" disabled={busy} onClick={()=>void act({action:'change',userId:confirm.member.id,role:confirm.role,generation:confirm.member.generation})}>Confirm change</button><button className="button secondary" onClick={()=>setConfirm(null)}>Cancel</button></div></section>}
 {data.role==='owner'&&<>{inviteOpen&&<form id="invite-teammate" className="asset-form member-invite-form" onSubmit={event=>{event.preventDefault();const id=key||crypto.randomUUID();setKey(id);void act({action:'invite',email,role,requestId:id,replaces:null});}}><h2>Invite a teammate</h2><label htmlFor="invite-email">Email</label><input ref={emailInput} id="invite-email" type="email" required maxLength={254} value={email} disabled={busy} onChange={event=>{setEmail(event.target.value);setKey('');}}/><label htmlFor="invite-role">Role</label><select id="invite-role" value={role} disabled={busy} onChange={event=>{setRole(event.target.value as WorkspaceRole);setKey('');}}>{roles.map(value=><option key={value} value={value}>{label(value)}</option>)}</select><p className="quiet">Viewer reads and exports. Contributor also adds assets, runs authorized checks and imports results. Owner also manages people and workspace settings.</p>{role==='owner'&&<p>Owner grants administrative access, including inviting and removing members.</p>}<p className="quiet">Joining does not authorize a check or create a payment obligation.</p><div className="actions"><button className="button" disabled={busy}>{busy?'Saving…':'Send invitation'}</button><button type="button" className="button secondary" disabled={busy} onClick={()=>setInviteOpen(false)}>Close</button></div></form>}<h2 className="members-section-title">Invitations</h2>{data.invitations.length===0?<p>No invitations yet.</p>:data.invitations.map(invite=><div className="member-row invitation-row" key={invite.id}><div><strong>{invite.recipient}</strong><p>{label(invite.role)} · <span className="member-role">{label(invite.state)}</span></p><p>{invite.deliveryState==='accepted'?(invite.provider==='file'?'Saved locally; email not sent':'Provider accepted (inbox delivery not confirmed)'):`Email: ${invite.deliveryState}`}</p><p>Expires {new Date(invite.expiresAt).toLocaleString()}</p></div>{['pending','expired'].includes(invite.state)&&<div className="actions"><button className="button secondary" disabled={busy} onClick={()=>void act({action:'resend',email:invite.recipient,role:invite.role,replaces:invite.id,requestId:crypto.randomUUID()})}>Resend</button><button className="button secondary" disabled={busy} onClick={()=>void act({action:'cancel',id:invite.id})}>Cancel invitation</button></div>}</div>)}</>}
 </>}</section>;
}
