import Link from 'next/link';
import { EditorialArticle, editorialBodyClass, editorialHeadingClass } from '@/components/editorial/editorial-article';
import { exposureSnapshotNote, editorialMetadata } from '@/lib/research';
export const metadata = editorialMetadata(exposureSnapshotNote);
export default function SnapshotNote() {
  return <EditorialArticle entry={exposureSnapshotNote}>
      <section className="pt-10"><h2 className={editorialHeadingClass.replace("mt-16", "mt-0")}>What did the check establish?</h2><p className={editorialBodyClass}>A public hostname can return useful evidence without supporting a conclusion about the security of the whole company. The free External Exposure Snapshot covers ten defined observations against one submitted hostname at a recorded time.</p><p className={editorialBodyClass}>Start with the named results: what needs attention, what was observed as expected, and what could not be determined. Collection completeness describes how much was observed. It is not a security grade.</p></section>
      <section><h2 className={editorialHeadingClass}>Read the observation before the conclusion</h2><p className={editorialBodyClass}>A missing response header is an observation under a bounded method, not evidence that an application is exploitable. A timeout leaves an unknown; it does not establish a vulnerability. An expected response does not establish that the hostname is secure.</p><p className={editorialBodyClass}>Needs-attention findings have no assigned security severity in the free snapshot. Informational observations remain visible without being promoted to vulnerabilities.</p></section>
      <section><h2 className={editorialHeadingClass}>Method and evidence</h2><p className={editorialBodyClass}>The application server performs bounded DNS, TLS and HTTP observations. TCP connections are restricted to public addresses on ports 80 and 443. The checks cover public resolution, certificate state, legacy TLS, the HTTP-to-HTTPS transition, HSTS, browser headers, security.txt, SPF, DMARC and CAA.</p><p className={editorialBodyClass}>Use the report to read the methods, evidence references and limitations together. The source JSON records the observations and request ledger. A request attempt is not a collected response. File hashes support integrity comparisons; they do not authenticate the observations or establish source-system truth. The free snapshot is unsigned.</p></section>
      <section><h2 className={editorialHeadingClass}>Limitations and unknowns</h2><p className={editorialBodyClass}>This is not a penetration test, complete attack-surface assessment, certification, compliance assessment or assurance opinion. It does not test authenticated functions, exploit vulnerabilities, inspect internal infrastructure or discover every subdomain. Public conditions can change after collection.</p><p className={editorialBodyClass}>A deeper human-reviewed investigation requires an agreed scope and authorization. It is separate from simply running more automated checks.</p></section>
      <section><h2 className={editorialHeadingClass}>Sources and next steps</h2><ul className="list-disc space-y-3 pl-5"><li><Link className="underline underline-offset-4" href="/check">External Exposure Snapshot: the ten-check workflow and its scope</Link></li><li><Link className="underline underline-offset-4" href="/review/sample-cases/external-exposure-assessment">External Attack Surface Review synthetic worked example</Link> — illustrative material, not a live customer assessment.</li><li><Link className="underline underline-offset-4" href="/catalog/offsec-external-exposure">External Attack Surface Review: authorized human-reviewed work</Link></li></ul><p className={editorialBodyClass}>To inspect your own hostname, <Link className="underline underline-offset-4" href="/check">open the free check</Link>. Only check a hostname you own or are authorized to check.</p></section>
  </EditorialArticle>;
}
